import cv2
from matplotlib import pyplot as plt
img = cv2.imread('img.png', 0)
laplacian = cv2.Laplacian(img, cv2.CV_64F)
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=5)
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=5)
schx = cv2.Scharr(img, cv2.CV_64F, 1, 0)
schy = cv2.Scharr(img, cv2.CV_64F, 0, 1)
plt.subplot(2, 3, 1), plt.imshow(img, cmap='gray'), plt.title('gray')
plt.subplot(2, 3, 2), plt.imshow(laplacian, cmap='gray'), plt.title('laplacian')
plt.subplot(2, 3, 3), plt.imshow(sobelx, cmap='gray'), plt.title('sobelx')
plt.subplot(2, 3, 4), plt.imshow(sobely, cmap='gray'), plt.title('sobely')
plt.subplot(2, 3, 5), plt.imshow(schx, cmap='gray'), plt.title('schx')
plt.subplot(2, 3, 6), plt.imshow(schy, cmap='gray'), plt.title('schy')
plt.show()
# sobelImg = cv2.add(sobelx, sobely)
# schImg = cv2.add(schx, schy)
# cv2.imshow("Original", img)
# cv2.imshow("laplacian", laplacian)
# cv2.imshow("Sobel", sobelImg)
# cv2.imshow("SCH", schImg)
cv2.waitKey()
cv2.destroyAllWindows()